### ISSUE TITLE
Issue downloading archaea genomes in RefSeq

### ISSUE THREAD

**Issue by Puumanamana** [kblin/ncbi-genome-download#118]
Hi,

I recently started using `ncbi-genome-download` for downloading some databases. It worked relatively well for bacteria (RefSeq). However, when I tried the same command for archaea, I got an error, not sure why it happends:

```bash
> ncbi-genome-download archaea --format fasta -s refseq

Traceback (most recent call last):
  File "/home/cedric/.py3Env/bin/ncbi-genome-download", line 8, in <module>
    sys.exit(main())
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/ncbi_genome_download/__main__.py", line 25, in main
    ret = args_download(args)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/ncbi_genome_download/core.py", line 159, in args_download
    return config_download(config)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/ncbi_genome_download/core.py", line 196, in config_download
    curr_jobs = create_downloadjob(entry, group, config)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/ncbi_genome_download/core.py", line 397, in create_downloadjob
    checksums = grab_checksums_file(entry)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/ncbi_genome_download/core.py", line 465, in grab_checksums_file
    req = requests.get(full_url)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/cedric/.py3Env/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'na/md5checksums.txt': No schema supplied. Perhaps you meant http://na/md5checksums.txt?
```

**Comment by kblin** [comment]
Hi, I think this is an issue fixed by #114, unfortunately I didn't get around to release a new version that includes the fix yet.

**Comment by Puumanamana** [comment]
You were right, it worked with the latest version.

Thank you

**Comment by mw55309** [comment]
Just ran into this problem download genbank protozoa, so how do I get this fix?

**Comment by jrjhealey** [comment]
It seems this traceback is cropping up a lot, there was a BioStars post about it just the other day: https://www.biostars.org/p/443814/#444411

Could NCBI have changed/broken something?

**Comment by kblin** [comment]
NCBI added entries to the assembly summary that don't have an FTP URL. The fix that just skips these entries is already in master, I just need to find time to release it.
