### ISSUE TITLE
Error using annotate

### ISSUE THREAD

**Issue by IsabelFE** [kblin/ncbi-genome-download#137]
Hello, 

I am getting the following error when trying to run the annotate module.

Could you help me with this? Thanks a lot!!

Isabel

`* [2020-10-07 18:35:58] : INFO  PanACoTA version 1.0-dev
  * [2020-10-07 18:35:58] : INFO  Command used
         > PanACoTA annotate -r Annotated_Genomes -n NCBI --info Genomes_NCBI/LSTINFO-Corynebacterium_bovis-filtered-0.0001_0.06.txt
  * [2020-10-07 18:35:58] : INFO  Reading given information on your genomes in Genomes_NCBI/LSTINFO-Corynebacterium_bovis-filtered-0.0001_0.06.txt
  * [2020-10-07 18:35:58] : INFO  Found 2 genomes in total
  * [2020-10-07 18:35:58] : INFO  Generating distribution of L90 and #contigs graphs.
  * [2020-10-07 18:35:59] : INFO  Renaming kept genomes according to their quality (2 genomes)
  * [2020-10-07 18:35:59] : INFO  Annotating all genomes with prokka
Traceback (most recent call last):
  File "/Users/isabelfe/opt/anaconda3/bin/PanACoTA", line 155, in <module>
    main()
  File "/Users/isabelfe/opt/anaconda3/bin/PanACoTA", line 21, in main
    action(args)
  File "/Users/isabelfe/opt/anaconda3/lib/python3.6/site-packages/PanACoTA/subcommands/annotate.py", line 155, in main_from_parse
    arguments.small)
  File "/Users/isabelfe/opt/anaconda3/lib/python3.6/site-packages/PanACoTA/subcommands/annotate.py", line 387, in main
    prodigal_only, small, quiet=quiet)
  File "/Users/isabelfe/opt/anaconda3/lib/python3.6/site-packages/PanACoTA/annotate_module/annotation_functions.py", line 109, in run_annotation_all
    term_width=100).start()
TypeError: __init__() got an unexpected keyword argument 'max_value'`

**Comment by jrjhealey** [comment]
Even though that tool uses ngd, this doesn't appear to be an error with ngd, instead it's failing to annotate with prokka.

You will probably need to raise this issue on the panacota github page.

**Comment by IsabelFE** [comment]
Hi, I am so sorry, I had both repos opened and asked on the wrong one. 🤦🏻‍♀️

**Comment by kblin** [comment]
No worries. 😄
