### ISSUE TITLE
issue with ncbi-genome-download

### ISSUE THREAD

**Issue by SrichandanPadhi** [kblin/ncbi-genome-download#226]
I am getting the following error with ncbi-genome-download. Please help me finding a solution.

COMMAND: $ ncbi-genome-download --taxids 511145 bacteria
ERROR:
Traceback (most recent call last):
  File "/home/srichandanp/miniconda3/envs/genome_analysis/bin/ncbi-genome-download", line 10, in <module>
    sys.exit(main())
  File "/home/srichandanp/miniconda3/envs/genome_analysis/lib/python3.5/site-packages/ncbi_genome_download/__main__.py", line 26, in main
    ret = args_download(args)
  File "/home/srichandanp/miniconda3/envs/genome_analysis/lib/python3.5/site-packages/ncbi_genome_download/core.py", line 174, in args_download
    return config_download(config)
  File "/home/srichandanp/miniconda3/envs/genome_analysis/lib/python3.5/site-packages/ncbi_genome_download/core.py", line 193, in config_download
    download_candidates = select_candidates(config)
  File "/home/srichandanp/miniconda3/envs/genome_analysis/lib/python3.5/site-packages/ncbi_genome_download/core.py", line 290, in select_candidates
    for entry in filter_entries(entries, config):
  File "/home/srichandanp/miniconda3/envs/genome_analysis/lib/python3.5/site-packages/ncbi_genome_download/core.py", line 336, in filter_entries
    if not config.is_compatible_assembly_accession(entry['assembly_accession']):
KeyError: 'assembly_accession'

**Comment by kblin** [comment]
This was fixed in `ncbi-genome-download` 0.3.2, released about a year ago, please update.
