### ISSUE TITLE
Using ncbi-genome-download package

### ISSUE THREAD

**Issue by ChillarAnand** [kblin/ncbi-genome-download#231]
**Describe the bug**
Unable to pass options to ngd.download()

```
Downloading genomes for fungi
Traceback (most recent call last):
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/envs/bio3.8/bin/kdb", line 8, in <module>
    sys.exit(main())
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/envs/bio3.8/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/envs/bio3.8/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/envs/bio3.8/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/envs/bio3.8/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/envs/bio3.8/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/chillaranand/projects/kraken-db-builder/kdb.py", line 130, in main
    download_genomes(context, db_type)
  File "/Users/chillaranand/projects/kraken-db-builder/kdb.py", line 116, in download_genomes
    ngd.download(group='bacteria', format='fasta')
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/envs/bio3.8/lib/python3.8/site-packages/ncbi_genome_download/core.py", line 165, in download
    config = NgdConfig.from_kwargs(**kwargs)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/envs/bio3.8/lib/python3.8/site-packages/ncbi_genome_download/config.py", line 325, in from_kwargs
    raise ValueError("Unrecognized option(s): {}".format(kwargs.keys()))
ValueError: Unrecognized option(s): dict_keys(['group', 'format'])
```

**Affected version**
0.3.3

**To Reproduce**

        ngd.download(group='bacteria', format='fasta')

**Expected behavior**
It should accept kwargs

**Additional context**
https://github.com/AvilPage/kraken-db-builder/

I am using ncbi-genome-download package for kraken-db-builder to download genomes.

**Comment by ChillarAnand** [comment]
I tried running the command via `subprocess.run`. Unfortunately, progress-bar details are not showing up when running via subprocess.

https://github.com/AvilPage/kraken-db-builder/blob/master/kdb.py#L121

**Comment by kblin** [comment]
the keyword args you're looking for are `groups` and `file_formats`.

**Comment by ChillarAnand** [comment]
That worked. Thank you!

<img width="1279" alt="Screenshot 2024-08-05 at 18 54 52" src="https://github.com/user-attachments/assets/ca8fd0bf-53ea-4e4e-883f-488ce6da165d">

If you can add this example to readme, that would be great.
