### ISSUE TITLE
ncbi-genome-download works with refseq for me, but not genbank

### ISSUE THREAD

**Issue by Laura-Alex** [kblin/ncbi-genome-download#234]
This might be the same issue as #224 .

I am trying to download a couple of prokaryotic genomes. Some are in Refseq and Genbank, others only in the latter. When specifying Genbank, the code does not work, even as just a dry run. For example:

This is a RefSeq genome; this code returns the expected result.
`ncbi-genome-download --section refseq bacteria -F fasta -r 5 -A GCF_001548395.1 -n`

This is a copy of the same genome, stored in GenBank. This code does not work and just...keeps going forever.
`ncbi-genome-download --section genbank bacteria -F fasta -r 5 -A GCA_001548395.1 -n`

Other things I have tried and did not work:
-using taxid instead
-moving `'--section genbank bacteria'` to the end of the code
-with and without `'-r 5'`

When I finally kill the process, this is the error result I get:
```

Traceback (most recent call last):
  File "/home/user/.conda/envs/environment/bin/ncbi-genome-download", line 10, in <module>
    sys.exit(main())
  File "/home/user/.conda/envs/environment/lib/python3.10/site-packages/ncbi_genome_download/__main__.py", line 26, in main
    ret = args_download(args)
  File "/home/user/.conda/envs/environment/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 184, in args_download
    return config_download(config)
  File "/home/user/.conda/envs/environment/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 203, in config_download
    download_candidates = select_candidates(config)
  File "/home/user/.conda/envs/environment/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 317, in select_candidates
    entries = parse_summary(summary_file)
  File "/home/user/.conda/envs/environment/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 436, in parse_summary
    return SummaryReader(summary_file)
  File "/home/user/.conda/envs/environment/lib/python3.10/site-packages/ncbi_genome_download/summary.py", line 13, in __init__
    while 'assembly_accession' not in line:
KeyboardInterrupt
```

I would appreciate your help!

**Comment by hellopeccat** [comment]
same
