### ISSUE TITLE
Problem installing version 0.2.3 on Biolinux8 (Virtualbox) [solved]

### ISSUE THREAD

**Issue by dutchscientist** [kblin/ncbi-genome-download#37]
I am trying to update ncbi-genome-download ona Biolinux8 (Ubuntu 14.04) virtualbox virtual computer. Installation and running keep on failing on the cryptography module.

Error messages when upgrading from 0.1.8 to 0.2.3:
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p6t82g/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pi1daZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-p6t82g/cryptography/

When I first uninstall version 0.1.8 and then install 0.2.3, I get the following when running "ncbi-genome-download --version"

Traceback (most recent call last):
  File "/usr/local/bin/ncbi-genome-download", line 7, in <module>
    from ncbi_genome_download.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/ncbi_genome_download/__init__.py", line 2, in <module>
    from ncbi_genome_download.core import (
  File "/usr/local/lib/python2.7/dist-packages/ncbi_genome_download/core.py", line 16, in <module>
    from requests.packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    from cryptography import x509
ImportError: No module named cryptography

But cryptography etc is installed normally.

It does work on a non-virtualbox Biolinux install? Not sure what is the best approach now?

**Comment by dutchscientist** [comment]
Solved, pffff.
